# Generated by Django 5.1.1 on 2024-09-24 19:03

import django.db.models.deletion
import votingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=36, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('date_voted', models.DateTimeField(auto_now_add=True)),
                ('voter_code', models.CharField(blank=True, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=votingApp.models.candidate_image_path)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApp.voter')),
            ],
            options={
                'unique_together': {('voter', 'position')},
            },
        ),
    ]
