# Generated by Django 5.1.1 on 2024-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0002_alter_voter_firstname_alter_voter_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
