# Generated by Django 5.1.1 on 2024-09-24 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0003_alter_ballot_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_voted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
