# Generated by Django 5.1.1 on 2024-10-08 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0009_alter_voter_date_voted_alter_voter_voter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_voted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
