# Generated by Django 5.1.1 on 2024-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0010_alter_voter_date_voted_alter_voter_voter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_voted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
