# Generated by Django 4.2.11 on 2026-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0014_auto_20260505_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='voter',
            name='votingApp_v_voter_c_4535d6_idx',
        ),
        migrations.AddField(
            model_name='position',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower values display first'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['voting_code'], name='votingApp_v_voting__760825_idx'),
        ),
    ]
