# Generated by Django 5.1.1 on 2024-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='voter',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
