# Generated by Django 5.1.1 on 2024-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0006_result_total_accredidated_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='timestamp',
            field=models.DateTimeField(default='2024-09-27 10:47:15 PM'),
        ),
    ]
