# Generated by Django 5.1.1 on 2024-10-08 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0008_remove_result_total_accredidated_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_voted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
