# Generated by Django 5.2.5 on 2026-05-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0011_alter_voter_date_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='votingApp.candidate'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='votingApp.position'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='votingApp.voter'),
        ),
        migrations.AlterField(
            model_name='result',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='votingApp.candidate'),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='votingApp.position'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_code',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['voter', 'position'], name='votingApp_b_voter_i_f9ba08_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['has_voted'], name='votingApp_v_has_vot_9a9bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['voter_code'], name='votingApp_v_voter_c_4535d6_idx'),
        ),
    ]
