# Generated by Django 5.2.5 on 2026-05-05 11:27

import random
import string
from django.db import migrations, models


def generate_voting_code(apps, schema_editor):
    """Generate unique 6-char voting codes for existing voters"""
    Voter = apps.get_model('votingApp', 'Voter')
    characters = string.ascii_uppercase + string.digits

    for voter in Voter.objects.filter(voting_code=''):
        while True:
            code = ''.join(random.choice(characters) for _ in range(6))
            if not Voter.objects.filter(voting_code=code).exists():
                voter.voting_code = code
                voter.save()
                break


def reverse_migration(apps, schema_editor):
    """Set voting_code to empty on reverse"""
    Voter = apps.get_model('votingApp', 'Voter')
    Voter.objects.all().update(voting_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0012_alter_ballot_candidate_alter_ballot_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voting_code',
            field=models.CharField(
                max_length=6,
                unique=True,
                blank=True,
                default='',
                editable=False
            ),
            preserve_default=False,
        ),
        migrations.RunPython(generate_voting_code, reverse_migration),
    ]
