# Generated by Django 5.2.5 on 2026-05-05 11:42

from django.db import migrations, models
import random
import string


def generate_voting_codes(apps, schema_editor):
    """Generate unique 6-char voting codes for existing voters"""
    Voter = apps.get_model('votingApp', 'Voter')
    characters = string.ascii_uppercase + string.digits

    for voter in Voter.objects.all():
        # Skip if already has a code
        if voter.voting_code:
            continue
        while True:
            code = ''.join(random.choice(characters) for _ in range(6))
            if not Voter.objects.filter(voting_code=code).exists():
                voter.voting_code = code
                voter.save(update_fields=['voting_code'])
                break


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('votingApp', '0013_auto_20260505_1227'),
    ]

    operations = [
        # Remove old deprecated voter_code column
        migrations.RemoveField(
            model_name='voter',
            name='voter_code',
        ),
    ]
